name: CI

on:
  workflow_dispatch:
  push:
    branches:
     - 'feature/**'

defaults:
  run:
    working-directory: .tests
    shell: bash
    
jobs:
    myjob:
        runs-on: ubuntu-latest
        name: My Job
        steps:
          - uses: actions/checkout@v4
            with:
              # We need to fetch all branches and commits so that Nx affected has a base to compare against.
              fetch-depth: 0
    
          - name: Derive appropriate SHAs for base and head for `nx affected` commands
            id: setSHAs
            uses: nrwl/nx-set-shas@v4
    
          - run: |
              echo "BASE: ${{ steps.setSHAs.outputs.base }}"
              echo "HEAD: ${{ steps.setSHAs.outputs.head }}"

          - name: Run changed-files with the commit of the last successful test workflow run
            id: changed-files
            uses: tj-actions/changed-files@v44
            with:
              base_sha: ${{ steps.setSHAs.outputs.base }}
              files: |
                **.ipynb
          - name: List all changed files markdown files
            if: steps.changed-files.outputs.any_changed == 'true'
            env:
              ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
            run: |
              for file in ${ALL_CHANGED_FILES}; do
                echo "$file was changed"
              done
        